# Generated by Django 5.0 on 2026-02-03 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_session', '0003_alter_checkpoint_files_processed'),
        ('task', '0005_task_original_code'),
        ('tasklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='line_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='analysis_session.analysissession'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='task.task'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['session', '-timestamp'], name='tasklog_tas_session_1c3368_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task', '-timestamp'], name='tasklog_tas_task_id_3964be_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['-timestamp'], name='tasklog_tas_timesta_779e89_idx'),
        ),
    ]
