# Generated by Django 5.0 on 2026-02-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklog', '0002_tasklog_file_path_tasklog_line_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='level',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='log_type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('error', 'Error'), ('warning', 'Warning')], default='info', max_length=10),
        ),
    ]
