"""
Pull request creation service module.

This module handles creating GitHub pull requests for verified fixes.
"""
from github import Github

from apps.github_integration.models import PullRequest
from apps.task.models import Task


class PRCreator:
    """
    Creates pull requests for verified fixes.
    """
    def __init__(self, github_client: Github):
        self.client = github_client
    
    def create_pull_request(
        self,
        task: Task,
        branch_name: str,
        owner: str,
        repo_name: str
    ) -> PullRequest:
        """
        Create a pull request for a verified fix.

        Args:
            task: Task with verified fix
            branch_name: Branch with fix
            owner: Repo owner
            repo_name: Repo name
        
        Returns:
            Pullrequest model instance.
        """
        repo = self.client.get_repo(f"{owner}/{repo_name}")

        # Generate PR title and description
        title = self._generate_title(task)
        description = self._generate_description(task)

        # Create PR
        pr = repo.create_pull(
            title=title,
            body=description,
            head=branch_name,
            base=repo.default_branch
        )

        # Save to database
        pr_record = PullRequest.objects.create(
            task=task,
            repository=task.repository,
            pr_number=pr.number,
            pr_url=pr.html_url,
            branch_name=branch_name,
            title=title,
            description=description,
            status='open'
        )

        print(f"✓ Created PR #{pr.number}: {title}")
        print(f"  URL: {pr.html_url}")
        
        return pr_record
    
    def _generate_title(self, task: Task) -> str:
        """
        Generate PR title.
        """
        return f"🔒 Fix {task.vulnerability_type} in {task.file_path.split('/')[-1]}"
    
    def _generate_description(self, task: Task) -> str:
        """
        Generate detailed PR description.
        """
        return f"""## Security Fix: {task.vulnerability_type}

### 🔍 Vulnerability Details
- **File:** `{task.file_path}`
- **Line:** {task.line_number}
- **Type:** {task.vulnerability_type}

### 📝 Description
{task.description}

### ✅ Fix Applied
{task.fix_code}

### 🧪 Verification
This fix has been automatically verified:
- ✅ Test generated to prove vulnerability existed
- ✅ Fix applied
- ✅ Test now passes

### 📎 Test Code
```python
{task.test_code}
```

### 🤖 Generated By
FixIt AI Security Agent

**Action Required:** Please review this automated fix before merging.
"""        
