# Generated by Django 5.0 on 2026-01-28 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0002_repository_analysis_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier for tracking', max_length=36, unique=True)),
                ('total_files', models.IntegerField(default=0)),
                ('files_analyzed', models.IntegerField(default=0)),
                ('files_failed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('vulnerabilites_found', models.IntegerField(default=0)),
                ('task_created', models.IntegerField(default=0)),
                ('prs_created', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checkpoint_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('create_prs', models.BooleanField(default=True, help_text='Automatically create PRs for verified fixes.')),
                ('max_files', models.IntegerField(default=25, help_text='Maximum number of files to analyze per session.')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to='repository.repository')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_number', models.IntegerField()),
                ('files_processed', models.JSONField(help_text='List of files processed already processed')),
                ('last_file_index', models.IntegerField()),
                ('state_data', models.JSONField(blank=True, help_text='Additional state data for recovery', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='analysis_session.analysissession')),
            ],
            options={
                'ordering': ['-checkpoint_number'],
            },
        ),
        migrations.AddIndex(
            model_name='analysissession',
            index=models.Index(fields=['session_id'], name='analysis_se_session_363fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='analysissession',
            index=models.Index(fields=['status'], name='analysis_se_status_169aad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkpoint',
            unique_together={('session', 'checkpoint_number')},
        ),
    ]
