# Generated by Django 5.0 on 2026-01-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_session', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysissession',
            old_name='vulnerabilites_found',
            new_name='vulnerabilities_found',
        ),
    ]
