# Generated by Django 5.0 on 2026-02-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_session', '0002_rename_vulnerabilites_found_analysissession_vulnerabilities_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='files_processed',
            field=models.JSONField(help_text='List of files already processed'),
        ),
    ]
