# Generated by Django 5.0 on 2026-02-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_session', '0003_alter_checkpoint_files_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='fixes_generated',
            field=models.IntegerField(default=0, help_text='Number of fixes generated'),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='tests_created',
            field=models.IntegerField(default=0, help_text='Number of tests generated'),
        ),
    ]
