# Generated by Django 5.0 on 2026-01-17 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0002_repository_analysis_progress'),
        ('task', '0003_task_fix_code_task_fix_status_task_test_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Github bot username', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this auth is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When credentials were added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp.')),
            ],
            options={
                'verbose_name': 'Github Authentication',
                'verbose_name_plural': 'Github Authentications',
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField(help_text='Github PR number')),
                ('pr_url', models.URLField(help_text='Full URL to the PR on Github')),
                ('branch_name', models.CharField(help_text='Name of the branch containing this fix.', max_length=255)),
                ('title', models.CharField(help_text='PR title', max_length=255)),
                ('description', models.TextField(help_text='PR description in markdown format')),
                ('status', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed'), ('draft', 'Draft')], default='open', help_text='Current PR status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When PR was created')),
                ('merged_at', models.DateTimeField(blank=True, help_text='When PR was merged (if applicable).', null=True)),
                ('repository', models.ForeignKey(help_text='The repository where PR was created.', on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='repository.repository')),
                ('task', models.ForeignKey(help_text='The task this PR fixes', on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='task.task')),
            ],
            options={
                'verbose_name': 'Pull Request',
                'verbose_name_plural': 'Pull Requests',
                'ordering': ['-created_at'],
                'unique_together': {('repository', 'pr_number')},
            },
        ),
    ]
