# Generated by Django 5.0 on 2026-01-03 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('vulnerability_type', models.CharField(choices=[('xss', 'Cross-Site Scripting'), ('sql_injection', 'SQL Injection'), ('csrf', 'CSRF'), ('hardcoded_secret', 'Hardcoded Secret'), ('command_injection', 'Command Injection'), ('path_traversal', 'Path Traversal'), ('insecure_deserialization', 'Insecure Deserialization')], max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=300, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('validating', 'Validating'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('false_positive', 'False Positive')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('applied_fix', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='repository.repository')),
            ],
        ),
    ]
