# Generated by Django 5.0 on 2026-01-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_vulnerability_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fix_code',
            field=models.TextField(blank=True, help_text='Generated fix code for the vulnerability'),
        ),
        migrations.AddField(
            model_name='task',
            name='fix_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Fix Generated'), ('applied', 'Fix Applied'), ('verified', 'Fix Verified'), ('failed', 'Fix Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='test_code',
            field=models.TextField(blank=True, help_text='Generated test that proves vulnerability exists'),
        ),
        migrations.AddField(
            model_name='task',
            name='test_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Test Generated'), ('failed', 'Test Failed'), ('passed', 'Test Passed'), ('error', 'Test Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='validation_message',
            field=models.TextField(blank=True, help_text='Details from test/fix validation'),
        ),
        migrations.AddField(
            model_name='task',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the fix was verified', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Number of times the fix has been retried'),
        ),
    ]
