# Generated by Django 5.0 on 2026-01-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_fix_code_task_fix_status_task_test_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('validating', 'Validating'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('false_positive', 'False Positive'), ('pr_created', 'PR Created')], default='pending', max_length=20),
        ),
    ]
