# Generated by Django 5.0 on 2026-01-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='original_code',
            field=models.TextField(blank=True, help_text='Original vulnerable code from the file'),
        ),
    ]
