# Generated by Django 5.0 on 2026-02-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_original_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fix_explanation',
            field=models.TextField(blank=True, help_text='Explanation of what was fixed and why'),
        ),
        migrations.AddField(
            model_name='task',
            name='pr_url',
            field=models.URLField(blank=True, help_text='URL of the created Pull Request', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level of the vulnerability', max_length=20),
        ),
    ]
