# Generated by Django 5.0 on 2026-01-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('repo_name', models.CharField(max_length=255)),
                ('repo_url', models.URLField(unique=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('error', 'Error'), ('paused', 'Paused')], default='idle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'unique_together': {('owner', 'repo_name')},
            },
        ),
    ]
