# Generated by Django 5.0 on 2026-01-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='analysis_progress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
